# version:  '3'
# services:
#   jupyterlab:
#       container_name: jupyterlab
#       image: jupyter/datascience-notebook:latest
#       volumes:
#         - .:/home/jovyan/work
#       ports:
#         - 8888:8888
#       user: root
#       environment:
#         JUPYTER_ENABLE_LAB: 'yes'

version:  '2.3'
services:
  jupyter:
      container_name: jupyter
      image: jupyter/datascience-notebook:latest
      env_file:
        - .env
      volumes:
        - ${LOCAL_WORKING_DIR}:/home/jovyan/work
        - ${LOCAL_DATASETS}:/home/jovyan/work/datasets
        - ${LOCAL_MODULES}:/home/jovyan/work/modules
        - ${LOCAL_SSL_CERTS}:/etc/ssl/notebook
      ports:
        - ${PORT}:8888
      runtime: nvidia
      user: root
      environment:
        JUPYTER_ENABLE_LAB: 'yes'
      command: "start-notebook.sh \
        --NotebookApp.token=${ACCESS_TOKEN} \
        --NotebookApp.certfile=/etc/ssl/notebook/jupyter.pem \
        --NotebookApp.allow_origin='*' \
        --NotebookApp.ip='0.0.0.0' "
# nvidia-smi && 

  nginxserver: 
    container_name: nginxserver 
    image: nginx
    links: 
      - jupyter
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.crt:/data/cert.crt
      - ./nginx.key:/data/key.key
    ports:
      - 80:80
      - 443:443
    volumes_from:
      - jupyter
    depends_on:
      - jupyter
# letsencrypt
# openssl req -new -newkey rsa:2048 -nodes -keyout server.key -out server.csr
# openssl req -new -C DE -s Bayern -L Munich -O TUM -OU ESPACE -newkey rsa:2048 -nodes -keyout letsencrypt.key -out letsencrypt.csr
# openssl req -new -subj "/C=DE/ST=Bayern/L=Munich/O=TUM Security/OU=ESPACE"  -newkey rsa:2048 -nodes -keyout letsencrypt.key -out letsencrypt.csr

# sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt
# sudo openssl req -x509 -nodes -days 365 -subj "/C=DE/ST=Bayern/L=Munich/O=TUM Security/OU=ESPACE"  -newkey rsa:2048 -keyout nginx.key -out nginx.crt
